version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: consolidation/robo
    versions:
    - 3.0.0
    - 3.0.2
